version: "3"
services:
    server:
        image: "node:8"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=developpement
        volumes:
            - ./server:/home/node/app
        ports:
            - 8081:5000
        command: "npm start"

    client:
        image: "node:8"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=developpement
        volumes:
            - ./client:/home/node/app
        ports:
            - 8082:3000
        command: "npm start"

    data_base:
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_USER=root
            - PMA_PASSWORD=root
        restart: always
        ports:
            - 8083:80
