version: "3.1"
services:
    server:
        image: "node:8"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=developpement
        volumes:
            - ./server:/home/node/app
        ports:
            - 8081:5000
        command: "npm start"

    client:
        image: "node:8"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=developpement
        volumes:
            - ./client:/home/node/app
        ports:
            - 8082:3000
        command: "npm start"

    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_USER: root
            MYSQL_PASSWORD: example
            PMA_USER: root
            PMA_PASSWORD: example
        restart: always
        ports:
         - 8083:80
